kamel:
  run:
    integration:
      api:
        dependencies: '[camel-rest,camel-undertow,camel-jackson,camel-swagger-java]'
        open-apis: '[openapi.yaml]'
        properties: '[camel.rest.port=8080]'
        traits: '[service.auto=false]'
