name: Camel K Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Setup Camel K Tools
      uses: nicolaferraro/camel-k-github-action@2baed3211c2ded95681d8efbcbacac9cebc43072
      with:
        cluster: none
    - name: Patch kamel
      run: |
        curl --silent -L https://github.com/nicolaferraro/camel-k-github-action/releases/download/v1.0-alpha.1/kamel --output kamel
        chmod a+x kamel
        mv kamel /home/runner/bin/kamel
    - name: Connect to remote cluster
      env:
        OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
        OPENSHIFT_PASSWORD: ${{ secrets.OPENSHIFT_PASSWORD }}
        OPENSHIFT_URL: ${{ secrets.OPENSHIFT_URL }}
      run: |
        oc login -u ${OPENSHIFT_USER} -p ${OPENSHIFT_PASSWORD} --server=${OPENSHIFT_URL} --insecure-skip-tls-verify
        oc new-project camel-k-api-staging || true
        oc project camel-k-api-staging

    - name: Deploy Minio Server
      run: |
        oc apply -f test/minio.yaml
        oc wait pod --for=condition=ready --timeout=5m -l app=minio

    - name: Deploy Integrations
      run: |
        kamel install --force
        kamel run test/MinioConfigurer.java API.java -t service.auto=false -p api.bucket=camel-k -p camel.rest.port=8080 --name api --profile OpenShift --wait
